---
# handlers file for deploy_web
- name: Restart Apache Debian
  service: name=nginx state=restarted
  when: ansible_os_family == "Debian"

- name: Restart Nginx RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
