---
# tasks file for deploy_web
- block: #========== Block For Debian ==============
    - name: Install Apache For Debian
      apt: name=apache2 state=latest
    - name: Start Web Server for Debian
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- block: #++++++++++ Block For RedHat +++++++++++
    - name: Install Nginx web Server for RedHat
      yum: name=nginx state=present
    - name: Start Web Server for RedHat
      service: name=nginx state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: GENERATE INDEX.HTML file
  template: src=index.j2  dest={{ destin_file }}/index.html  mode=0555
  notify:
    - Restart Apache Debian
    - Restart Nginx RedHat

- name: Copy Img
  copy: src={{ item }} dest={{ destin_file }} mode=0555
  loop:
    - "1.jpg"

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://10.0.2.9:80
    return_content: yes
  register: this
  failed_when: "'We did it' not in this.content"
  when: ansible_os_family == 'Debian'

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://10.0.2.9:80
    return_content: yes
  register: this
  failed_when: "'We did it' not in this.content"
  when: ansible_os_family == 'RedHat'
